Split go apps
betterme-dev/go-server-core pull request #35
Opened 2021-02-18 10:55 UTC by stanislav-bmw

- move shared services to pkg/lib
- add db/goqu
- add conf for logger and mq

2021-02-18 10:56 UTC, stanislav-bmw commented
[предложение](https://github.com/betterme-dev/backend-calorietracker-service/pull/2) от @artygan

2021-02-18 12:55 UTC, aksafan requested changes
Мне нравится тренд на выделение общего функционала из бекэнд-сервисов.
Хорошо, что сразу пакеты разделены по условным либам, в будущем их будет проще выделять в отдельные пакеты при разрастании функционала.

По фиксам только мультисессии и чуток косметике.

В целом все найс!

2021-02-18 12:55 UTC, aksafan commented on pkg/lib/image/service.go
> +func (s Service) ImagesByIds(ids []uint64, quality Quality) ([]ImageFile, error) {
Я не совсем в контексте работы с картинками, но предполагаю, что эта логика юзается в 2+ местах в бекэнд-сервисах и по этому она выносится сюда.

Если так, то в принципе ок. Пока тут мало логики для отдельного пакетаю

2021-02-18 12:55 UTC, aksafan commented on pkg/lib/image/service.go
> +func notFoundImages(ids []uint64, images []ImageFile) []uint64 {
Для нахождения пересечения я как-то юзал эту [либу](https://github.com/juliangruber/go-intersect), может будет удобнее двух вложенных циклов.

2021-02-18 12:55 UTC, aksafan commented on pkg/lib/image/structures.go
> +type (
Может все типы внутрь одних скобок?

2021-02-18 12:55 UTC, aksafan commented on pkg/lib/user/repository.go
> +func (r Repository) GetByAuthKey(authKey string) (*User, error) {
Сюда еще выборки по мультисессиям нужно добавить.

2021-02-18 18:30 UTC, stanislav-bmw commented on pkg/lib/image/service.go
> +func notFoundImages(ids []uint64, images []ImageFile) []uint64 {
тут наоборот - расхождение. погуглил, ничего нормального не нашёл.
написал свой костыль...
```go
func In(needle interface{}, haystack []interface{}) bool {
	for _, v := range haystack {
		if v == needle {
			return true
		}
	}
	return false
}

func Diff(a []interface{}, b []interface{}) []interface{} {
	var r []interface{}
	for _, v := range a {
		if !In(v, b) {
			r = append(r, b)
		}
	}
	return r
}
```
поймал `[]uint64 to []interface{} conversion error`... успокоился и ревертнул :)

2021-02-18 18:30 UTC, stanislav-bmw commented on pkg/lib/image/structures.go
> +type (
fixed

2021-02-18 18:30 UTC, stanislav-bmw commented on pkg/lib/user/repository.go
> +func (r Repository) GetByAuthKey(authKey string) (*User, error) {
fixed

2021-02-19 08:24 UTC, artygan approved these changes

2021-02-19 09:33 UTC, stanislav-bmw commented on pkg/lib/image/interface.go
> +		ImagesByIds(ids []uint64, quality Quality) ([]ImageFile, error)
поменял на uint

2021-02-19 09:33 UTC, stanislav-bmw commented on pkg/lib/auth/service.go
> +func (s *Service) AuthByBearerToken(token string) bool {
добавил

2021-02-19 12:00 UTC, aksafan approved these changes
По типам пару моментов глянь плз, а так ок.

2021-02-19 12:00 UTC, aksafan commented on pkg/lib/user/structures.go
> +		AuthKeyExpires int64 `db:"auth_key_expires"`
Тут конечно так и было с int64, но раз мы уже меняем все, то есть варик попробовать чистым интом. Ну и ниже так же.

2021-02-19 12:01 UTC, aksafan commented on pkg/lib/image/service.go
> +func notFoundImages(ids []uint64, images []ImageFile) []uint64 {
Азах, оке)

2021-02-19 12:02 UTC, stanislav-bmw commented on pkg/lib/user/structures.go
> +		AuthKeyExpires int64 `db:"auth_key_expires"`
я поменяю, но могут быть проблемы с маппингом с дб.

2021-02-19 12:02 UTC, stanislav-bmw commented on pkg/lib/user/repository.user-session.go
> +package user
ок, андерскор.

2021-02-19 12:09 UTC, merged